server:
  port: 18081

dubbo:
  registry:
    # 挂载到 Spring Cloud 注册中心
    address: spring-cloud://localhost
  cloud:
    subscribed-services: sca-provider
  consumer:
    check: false

spring:
  cloud:
    nacos:
      # Nacos 服务注册发现
      discovery:
        server-addr: 127.0.0.1:8848


